---

vault_wp_db_name: wordpressdb    # not-secret
vault_wp_db_user: wpuser         # not-secret
# wp_db_password_vault and wp_admin_password_vault are injected via the rhis_wordpress_operator AAP credential type
