# A valid mac is required when using bare metal as compute resource
# this can come from a query of satellites available discovered hosts or
# be a known value - for all other compute resources, the mac is assigned by
# the compute resource
discovered_hosts_resource: "discovered_hosts"
discovered_hosts_search: "disk_count = 1 and memory > 32000"
discovered_host_req_nic_count: 1  # we use > below so does not include lo
host_build_comment: "Created by ansible for content test"
enable_debug_logging: false
deploy: true
post_deploy_timeout: 600
use_sync_build: false


# Base network info
_default_domain_lab: "parmstrong.ca"
_default_subnetname_lab: "labsubnet"
_default_provision_iface_lab: "eno1"
_default_vm_provision_iface_lab: "ens192"

# Bond network
_default_bond_subnetname_lab: "bond_subnet"
_default_bond_subnet_prefix_lab: 23
_default_bond_default_gateway_lab: 192.168.252.1
_default_bond_iface_lab: "bond0"
_default_child_iface1_lab: "enp2s0f0"
_default_child_iface2_lab: "enp2s0f1"
# _default_bond_vlan_tag_meta: "940"
