---

# NOTE: Baremetal requires a valid MAC or the dhostname to provision a discovered host
#  - Supplying a MAC will search for a discovered host with that MAC address
#  - Providing "ff:ff:ff:ff:ff:ff" will use search criteria to find the first host to match
#  - Providing the "name" of the discovered host as dhostname will select the host with that dhostname

# platform_hosts:
#   - name: "bondtest2"
#     fqdn: "bondtest2.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel8_metal"
#     kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
#     compute_resource: "baremetal"
#     interfaces_attributes:
#       - type: "interface"
#         identifier: "{{ _default_provision_iface_lab }}"
#         domain: "{{ _default_domain }}"
#         execution: true
#         managed: true
#         primary: true
#         provision: true
#         subnet: "{{ _default_subnetname }}"
#         mac: "c0:3f:d5:64:72:10"
#         ip: "192.168.252.239"
#       - type: "interface"
#         identifier: "{{ _default_child_iface1_lab }}"
#         mac: "00:30:18:c5:c3:e4"
#       - type: "interface"
#         identifier: "{{ _default_child_iface2_lab }}"
#         mac: "00:30:18:c5:c3:e5"
#       - type: "bond"
#         identifier: "{{ _default_bond_iface_lab }}"
#         name: "bondtest2bond0"
#         domain: "{{ _default_domain_lab }}"
#         execution: false
#         managed: true
#         primary: false
#         provision: false
#         ip: "192.168.254.239"
#         subnet: "{{ _default_bond_subnetname }}"
#         attached_devices:
#           - "{{ _default_child_iface1_lab }}"
#           - "{{ _default_child_iface2_lab }}"
#         bond_options: "miimon=100 xmit_hash_policy=layer3+4"
#         mode: "802.3ad"
#         virtual: true
#        # tag: "{{ _default_bond_vlan_tag_meta }}"

  # - name: "pucci"
  #   fqdn: "pucci.parmstrong.ca"
  #   delete_host: false
  #   organization: "Default Organization"
  #   location: "Default Location"
  #   hostgroup: "hg_x86_64_rhel8_metal/CIS2Encrypted/RAID"
  #   kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
  #   compute_resource: "baremetal"
  #   serial: "MySerialNumber"
  #   rack: "MyRackId"
  #   mac: "94:C6:91:1F:22:6E"
  #   ip: "192.168.252.78"
  #   trunk_mac1: "7C:C2:55:6B:49:DA"
  #   trunk_mac2: "7C:C2:55:6B:49:D4"
  #   trunk_ip: "10.161.40.201"
  #   bmc_mac: "7C:C2:55:E2:CD:FC"
