---
# CreateHostFromHostGroup.yml
# This play creates a host of a defined name from a defined hostgroup
# we can't gather facts because the hosts dont exist yet

- name: Create hosts from specified Satellte/Foreman hostgroups
  hosts: provisioner
  gather_facts: false

  tasks:

    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Build the specified hosts"
      ansible.builtin.include_role:
        name: platform_node_build
