---
# Delete Host using Satellite
- name: "Delete hosts from specified Satellte/Foreman hostgroups"
  hosts: provisioner
  gather_facts: false

  tasks:
    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Load the vault variables"
      when: vault_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vault_dir }}"

    - name: "Load the other variables"
      when: vars_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vars_dir }}"

    - name: "Delete the host"
      ansible.builtin.include_tasks: tasks/delete_host.yml
      loop: "{{ host_list }}"
      loop_control:
        loop_var: delete_host
