---

collections:
  - name: community.general
    version: "9.3.0"
  - name: "community.mysql"
    version: "3.11.0"
  - name: "ansible.netcommon"
    version: "7.1.0"
  - name: "ansible.posix"
    version: "1.5.4"
  - name: "ansible.utils"
    version: "5.1.2"
  - name: "ansible.controller"
    version: "4.5.21"
  - name: "redhat.rhel_idm"
    version: "1.11.1"
  - name: "redhat.satellite"
    version: "5.0.0"
  - name: "redhat.satellite_operations"
    version: "2.1.0"
  - name: "redhat.rhel_system_roles"
    version: "1.23.0"
  - name: "community.vmware"
    version: "3.9.0"
