---

collections:
  - name: "ansible.netcommon"
  - name: "ansible.posix"
  - name: "ansible.utils"
  - name: "ansible.controller"
    version: "<4.6"
  - name: "ansible.hub"
  - name: "community.general"
  - name: "community.mysql"
  - name: "community.vmware"
  - name: "redhat.satellite"
    version: ">=5.0"
  - name: "redhat.rhel_system_roles"
