---
# This play undeploys a sample app previously deployed by the main.yml play
# This checks for the deployed app on the server
# If found, undeploys it. If not, exits assuming it is already gone.
#
- name: Undeploy a previously deployed sample app
  hosts: all
  tasks:

    - name: "Ensure JBoss EAP is running"
      ansible.builtin.service:
        name: "eap7-standalone.service"
        enabled: true
        state: started

    - name: "Ensure that we deployed the app"
      ansible.builtin.stat:
        path: "{{ app_fingerprint }}"
      register: fingerprint

    - name: Undeploy the app if our fingerprints exist
      when: fingerprint.stat.exists
      block:

        - name: "Undeploy the sample app"
          ansible.builtin.command:
            chdir: "{{ sample_app_root }}/{{ sample_app_dir }}"
            cmd: "mvn wildfly:undeploy"
          register: maven_undeploy
          changed_when: maven_undeploy.rc == 0

        - name: "Ensure that firewalld is started"
          ansible.builtin.service:
            name: "firewalld"
            state: "started"

        - name: "Close the firewall ports used"
          ansible.posix.firewalld:
            port: "{{ port_protocol }}"
            state: "disabled"
            immediate: true
            permanent: true
          loop:
            - "{{ http_port }}/tcp"
            - "{{ https_port }}/tcp"
          loop_control:
            loop_var: port_protocol

        - name: "Clean up fingerprints"
          ansible.builtin.file:
            path: "{{ app_fingerprint }}"
            state: absent
