---
# Deploy and configure php

- name: "Ensure the prerequisites"
  ansible.builtin.include_tasks:
    file: "prerequisites.yml"

- name: "Deploy the configuration"
  ansible.builtin.include_tasks:
    file: "deploy.yml"
