---

- name: "Install the php modules for RHEL 9"
  when: ansible_distribution_major_version == "9"
  ansible.builtin.dnf:
    name: "@php:8.2/common"
    state: "present"

- name: "Install the php modules for RHEL 8"
  when: ansible_distribution_major_version == "8"
  ansible.builtin.dnf:
    name: "@php:7.4/common"
    state: "present"
