---
postgresql_port: 5432
postgresql_db_name: "northwind"
postgresql_app_user: "northwind_app"
postgresql_bind_address: "0.0.0.0"
postgresql_hba_entries:
  - type: host
    database: "{{ postgresql_db_name }}"
    user: "{{ postgresql_app_user }}"
    address: "0.0.0.0/0"
    method: "md5"
...
