---
# This role expects a list of content views as input. See sample variables in vars/all.yml
# Please remember that CV and CCV promotion can be long running tasks depending on version and configuration of Satellite
# TODO: implement skip if date is the same and force to publish regardless

- name: Promote the content views when required
  when: force_promote
  block:
    - name: Promote the configured content views
      redhat.satellite.content_view_version:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_url }}"
        organization: "{{ satellite_organization }}"
        validate_certs: "{{ satellite_validate_certs }}"
        content_view: "{{ item.name }}"
        description: "{{ description }}"
        current_lifecycle_environment: "{{ source_lce }}"
        lifecycle_environments: "{{ target_lce }}"
      loop: "{{ content_views | default([], true) }}"

    - name: Promote the configured composite content views
      redhat.satellite.content_view_version:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_url }}"
        organization: "{{ satellite_organization }}"
        validate_certs: "{{ satellite_validate_certs }}"
        content_view: "{{ item.name }}"
        description: "{{ description }}"
        current_lifecycle_environment: "{{ source_lce }}"
        lifecycle_environments: "{{ target_lce }}"
      loop: "{{ composite_content_views | default([], true) }}"
