---
# vmw_reboot_guest_os.yml

- name: Reboot the OS on the list of vmware hosts
  hosts: provisioner
  
  vars:
    power_action_target_state: "reboot-guest"

  tasks:

    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Set the power state"
      ansible.builtin.include_tasks: "tasks/power_action.yml"
      loop: "{{ host_list }}"
      loop_control:
        loop_var: host
