---
# vmw_power_on_vm.yml

- name: Power on the list of vmware hosts
  hosts: all
  vars:
    power_action_target_state: "powered-on"

  tasks:

    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Set the power state"
      ansible.builtin.include_tasks: tasks/power_action.yml
