---
# vmw_remove_all_snapshots.yml

- name: Delete all the vm snapshots for the list of hosts
  hosts: provisioner
  
  vars:
    snapshot_target_state: "remove_all"

  tasks:

    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Set the snapshot state"
      ansible.builtin.include_tasks: "tasks/snapshot_action.yml"
      loop: "{{ host_list }}"
      loop_control:
        loop_var: host
