---
# Process the content views
- name: "Process Content View"
  ansible.builtin.include_tasks: "process_cv.yml"
  loop: "{{ content_views }}"
  loop_control:
    loop_var: cv

# Process the composites after all the content views finish
# This ensures consistency and single publication
- name: "Process Composite Content View {{ cv.name }}"
  ansible.builtin.include_tasks: "process_cv.yml"
  loop: "{{ composite_content_views }}"
  loop_control:
    loop_var: cv
